### ISSUE TITLE
next.js / ビルドでエラーが発生する

### ISSUE THREAD

**Issue by localer** [ryoppippi/unplugin-typia#133]
開発環境(`next dev`): 問題なし
ビルド(`next build`): エラーで止まってしまう

```diff
@localer ➜ /workspaces/lupus (codespaces) $ npm run build

> lupus@0.1.0 build
> next build

  ▲ Next.js 14.2.4
  - Environments: .env.local, .env

   Creating an optimized production build ...

 ╭──────────────────────────────────╮
 │                                  │
 │  [unplugin-typia] Cache enabled  │
 │                                  │
 ╰──────────────────────────────────╯

- <w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /workspaces/lupus/node_modules/mlly/dist/index.mjs for build dependencies failed at 'import(dataURL)'.
- <w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.

 ╭──────────────────────────────────╮
 │                                  │
 │  [unplugin-typia] Cache enabled  │
 │                                  │
 ╰──────────────────────────────────╯

- unhandledRejection Error: module is a string value; tsconfig JSON must be parsed with parseJsonSourceFileConfigFileContent or getParsedCommandLineOfConfigFile before passing to createProgram
-     at Object.createProgram (/workspaces/lupus/node_modules/@ryoppippi/unplugin-typia/node_modules/typescript/lib/typescript.js:123997:15)
-    at getProgramAndSource (file:///workspaces/lupus/node_modules/@ryoppippi/unplugin-typia/dist-esm/core/typia.js:86:24)
-    at transformTypia (file:///workspaces/lupus/node_modules/@ryoppippi/unplugin-typia/dist-esm/core/typia.js:30:41)
-    at async Object.transform (file:///workspaces/lupus/node_modules/@ryoppippi/unplugin-typia/dist-esm/core/index.js:45:24)
-    at async Object.transform (/workspaces/lupus/node_modules/unplugin/dist/webpack/loaders/transform.js:108:15)
```

**Comment by localer** [comment]
原因がわかりました
なにかの弾みで `@ryoppippi/unplugin-typia` 内の `typescript` のバージョンが、`5.4.5` から `5.5.2` に変わってました。

![image](https://github.com/ryoppippi/unplugin-typia/assets/96213511/c30d707e-5424-47a5-866b-16a1b694e127)

お騒がせしました
