### ISSUE TITLE
How to use typia with Vite / Vue

### ISSUE THREAD

**Issue by wienczny** [ryoppippi/unplugin-typia#266]
I'm integrating typia into my vue project using unplugin-typia. 
I get the following error when running "npm run build":

`WebstormProjects/typia-example/src/components/HelloWorld.vue?vue&type=script&setup=true&lang.ts:59:0: ERROR: Unexpected ")"
file: .../typia-example/src/components/HelloWorld.vue?vue&type=script&setup=true&lang.ts:59:0

Unexpected ")"
57 |      }
58 |  });
59 |  )
   |  ^

    at failureErrorWithLog (.../typia-example/node_modules/esbuild/lib/main.js:1472:15)
    at .../typia-example/node_modules/esbuild/lib/main.js:755:50
    at responseCallbacks.<computed> (.../typia-example/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (.../typia-example/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (.../typia-example/node_modules/esbuild/lib/main.js:600:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:191:23)`

I setup a small sample project using the vuejs template and applying the setup instruction for unplugin-typia
https://github.com/wienczny/typia-example

There is already a similar issue related to react at https://github.com/samchon/typia/issues/1178

**Comment by ryoppippi** [comment]
currently, vue SFC is not supported https://github.com/ryoppippi/unplugin-typia/issues/3
If you are interested it, please contribute it

**Comment by ryoppippi** [comment]
If you are interested in, PRs are welcome !!w @wienczny

**Comment by gvlasov** [comment]
The workaround is to not put the typia call into the `script` section of a SFC component, and instead define a function that uses the typia call in another `.ts` file and import it to the SFC component.
