### ISSUE TITLE
Vite ERR_REQUIRE_ESM error.

### ISSUE THREAD

**Issue by sgpinkus** [ryoppippi/unplugin-typia#355]
### unplugin-typia version

1.1.0

### What platform is your computer? Copy the output of `npx envinfo --system -npmPackages cleye --binaries`

  System:     OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)     CPU: (12) x64 12th Gen Intel(R) Core(TM) i3-1220P     Memory: 5.81 GB / 11.38 GB     Container: Yes     Shell: 5.1.4 - /bin/bash   Binaries:     Node: 22.1.0 - /usr/local/bin/node     Yarn: 1.22.19 - /usr/local/bin/yarn     npm: 10.7.0 - /usr/local/bin/npm

### Describe the bug

Followed instructions [here](https://typia.io/docs/setup/#unplugin-typia) for Vite. Getting:

```
$ npm exec vite
The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
failed to load config from /home/node/vite.config.ts
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/node/node_modules/@ryoppippi/unplugin-typia/src/vite.js from /home/node/vite.config.ts not supported.
Instead change the require of vite.js in /home/node/vite.config.ts to a dynamic import() which is available in all CommonJS modules.
    at _require.extensions.<computed> [as .js] (file:///home/node/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:53876:9)
    at Object.<anonymous> (/home/node/vite.config.ts:40:28)
    at _require.extensions.<computed> [as .js] (file:///home/node/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:53874:16)
```

### Reproduction

Still trying to reproduce. Will post when get it. If I do `npm init  vue@latest` and run through same instructions everything works fine. Not sure what is different about my project. All versions are the same and tsconfig seem practically identical.

### Validations

- [X] Check that there isn't [already an issue](https://github.com/ryoppippi/unplugin-typia/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sgpinkus** [comment]
Oh. The difference was my broken project did not have ` "type": "module"` field in package.json!

P.S. Man I HATE that field!
